#!/usr/bin/env sh
source ~/.cache/wal/colors.sh

#Passive colors
p1="${color8:1}"

#active colors - (same as position on bar)
c1="${color2:1}"
c2="${color4:1}"
c3="${color3:1}"
c4="${color9:1}"
c5="${color5:1}"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config active_window_opacity        0.75
yabai -m config normal_window_opacity        0.80
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# Boarders 
yabai -m config window_border on
yabai -m config window_border_width 10
yabai -m config active_window_border_color 0xff$c4
yabai -m config normal_window_border_color 0xff$p1

# general space settings
yabai -m config layout                       bsp
yabai -m config external_bar                 all:28:0
yabai -m config top_padding                  30   #30
yabai -m config bottom_padding               30   #30
yabai -m config left_padding                 30   #30
yabai -m config right_padding                30   #30
yabai -m config window_gap                   30   #30

# Running through float windows

yabai -m config --space 5 layout             float
yabai -m config --space 6 layout             float

# App rules
yabai -m rule --add app=Spotify space=1
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app=Dashlane manage=off
yabai -m rule --add app=Übersicht manage=off

yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=window_title_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=application_activated \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"



echo "yabai configuration loaded.."
